options:
    merge-default-rules: false
    formatter: stylish
    max-warnings: 0

# files:
#   ignore:
#     - 'sass/vendor/**/*.*'

rules:
    attribute-quotes:
        - 1
        -
            include: true
    # bem-depth: 0
    border-zero:
        - 1
        -
            convention: 'none'
    brace-style:
        - 1
        -
            style: '1tbs'
            allow-single-line: true
    class-name-format:
        - 1
        -
            allow-leading-underscore: false
            convention: 'hyphenatedlowercase'
            ignore: ['uk-height-1-1\@s']
            # convention-explanation: 'konvence: vse malym, pomlcky jako oddelovace'
    clean-import-paths:
        - 1
        -
            leading-underscore: false
            filename-extension: false
    # declarations-before-nesting: 0
    empty-args:
        - 1
        -
            include: true
    empty-line-between-blocks:
        - 1
        -
            include: true
            allow-single-line-rulesets: true
    # extends-before-declarations: 1
    # extends-before-mixins: 1
    final-newline:
        - 1
        -
            include: true
    # force-attribute-nesting: 0
    # force-element-nesting: 0
    # force-pseudo-nesting: 0
    function-name-format:
        - 1
        -
            allow-leading-underscore: false
            convention: 'hyphenatedlowercase'
            # convention-explanation: 'konvence: vse malym, pomlcky jako oddelovace'
    hex-length:
        - 1
        -
            style: short
    hex-notation:
        - 1
        -
            style: lowercase
    # id-name-format: 0
    indentation:
        - 1
        -
            size: 4
    leading-zero:
        - 1
        -
            include: true
    # max-file-line-count: 0
    # max-line-length: 0
    mixin-name-format:
        - 1
        -
            allow-leading-underscore: false
            convention: 'hyphenatedlowercase'
            # convention-explanation: 'konvence: vse malym, pomlcky jako oddelovace'
    # mixins-before-declarations: 0
    nesting-depth:
        - 1
        -
            max-depth: 4
    # no-attribute-selectors: 0
    # no-color-hex: 0
    no-color-keywords: 1
    # no-color-literals:
    #   - 1
    #   -
    #     allow-map-identifiers: true
    #     allow-rgba: true
    #     allow-variable-identifiers: true
    # no-combinators: 0
    no-css-comments: 1
    no-debug: 1
    # no-disallowed-properties: 0
    no-duplicate-properties: 1
    no-empty-rulesets: 1
    no-extends: 1
    no-ids: 1
    no-important: 1
    no-invalid-hex: 1
    no-mergeable-selectors:
        - 1
        # -
        #   whitelist: ...
    no-misspelled-properties: 1
    # no-qualifying-elements: 0
    no-trailing-whitespace: 1
    no-trailing-zero: 1
    # no-transition-all: 0
    # no-universal-selectors: 0
    # no-url-domains: 0
    # no-url-protocols: 0
    no-vendor-prefixes:
        - 1
        -
            ignore-non-standard: true
            # additional-identifiers: ...
            # excluded-identifiers: ...
    no-warn: 1
    one-declaration-per-line: 1
    # placeholder-in-extend: 1
    placeholder-name-format:
        - 1
        -
            allow-leading-underscore: false
            convention: 'hyphenatedlowercase'
            # convention-explanation: 'konvence: vse malym, pomlcky jako oddelovace'
    # property-sort-order: 0
    property-units:
        - 1
        -
            global: ['px', '%', 'em', 'rem', 's', 'ms', 'vw', 'vh']
            # per-property: ...
    pseudo-element: 1
    quotes:
        - 1
        -
            style: 'double'
    shorthand-values: 1
    single-line-per-selector: 1
    space-after-bang:
        - 1
        -
            include: false
    space-after-colon:
        - 1
        -
            include: true
    space-after-comma:
        - 1
        -
            include: true
    space-around-operator:
        - 1
        -
            include: true
    space-before-bang:
        - 1
        -
            include: true
    space-before-brace:
        - 1
        -
            include: true
    space-before-colon:
        - 1
        -
            include: false
    space-between-parens:
        - 1
        -
            include: false
    trailing-semicolon:
        - 1
        -
            include: true
    url-quotes: 1
    # variable-for-property: 0
    variable-name-format:
        - 1
        -
            allow-leading-underscore: false
            convention: 'hyphenatedlowercase'
            # convention-explanation: 'konvence: vse malym, pomlcky jako oddelovace'
    zero-unit:
        - 1
        -
            include: false
